# Generated by Django 6.0.1 on 2026-01-15 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0008_order_is_custom_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomOrderRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                ("colors", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "images",
                    models.JSONField(default=list, help_text="List of image URLs"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved - Awaiting Payment"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid - In Production"),
                            ("in_production", "In Production"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes on pricing/timeline/rejection reason",
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quoted price in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stripe_payment_link", models.URLField(blank=True, null=True)),
                (
                    "stripe_payment_intent",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Payment Intent ID after payment",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_request",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Order Request",
                "verbose_name_plural": "Custom Order Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
