# Generated by Django 6.0.1 on 2026-01-16 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customorderrequest",
            name="quoted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quoted price in USD",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
