# Generated by Django 4.2.7 on 2026-01-05 00:35

from django.db import migrations


def convert_lighter_type_to_int(apps, schema_editor):
    """Convert string lighter_type values to integer constants"""
    OrderItem = apps.get_model('orders', 'OrderItem')
    
    # Convert existing string values to integer constants
    OrderItem.objects.filter(lighter_type='classic').update(lighter_type=1)
    OrderItem.objects.filter(lighter_type='mini').update(lighter_type=2)


def convert_lighter_type_to_string(apps, schema_editor):
    """Convert integer lighter_type values back to string constants"""
    OrderItem = apps.get_model('orders', 'OrderItem')
    
    # Convert integer values back to string constants
    OrderItem.objects.filter(lighter_type=1).update(lighter_type='classic')
    OrderItem.objects.filter(lighter_type=2).update(lighter_type='mini')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_lighter_type'),
    ]

    operations = [
        migrations.RunPython(convert_lighter_type_to_int, convert_lighter_type_to_string),
    ]
