# Generated by Django 4.2.7 on 2026-01-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_convert_lighter_type_to_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='lighter_type',
            field=models.IntegerField(choices=[(1, 'Classic BIC'), (2, 'Mini BIC')], default=1, help_text='Lighter type at time of purchase (snapshot)'),
        ),
    ]
