# Generated by Django 4.2.7 on 2026-01-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_lighter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='lighter_type',
        ),
    ]
