# Generated by Django 6.0.1 on 2026-01-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_orderitem_lighter_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_custom_order",
            field=models.BooleanField(
                default=False, help_text="Whether this is a custom order"
            ),
        ),
    ]
