# Generated by Django 4.2.7 on 2025-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_currency_product_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD - US Dollar'), ('eur', 'EUR - Euro'), ('gbp', 'GBP - British Pound'), ('cad', 'CAD - Canadian Dollar'), ('aud', 'AUD - Australian Dollar'), ('jpy', 'JPY - Japanese Yen'), ('chf', 'CHF - Swiss Franc')], default='usd', max_length=10),
        ),
    ]
