# Generated by Django 4.2.7 on 2026-01-05 00:36

from django.db import migrations


def convert_lighter_type_to_int(apps, schema_editor):
    """Convert string lighter_type values to integer constants"""
    Product = apps.get_model('products', 'Product')
    
    # Convert existing string values to integer constants
    Product.objects.filter(lighter_type='classic').update(lighter_type=1)
    Product.objects.filter(lighter_type='mini').update(lighter_type=2)


def convert_lighter_type_to_string(apps, schema_editor):
    """Convert integer lighter_type values back to string constants"""
    Product = apps.get_model('products', 'Product')
    
    # Convert integer values back to string constants
    Product.objects.filter(lighter_type=1).update(lighter_type='classic')
    Product.objects.filter(lighter_type=2).update(lighter_type='mini')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_lighter_type'),
    ]

    operations = [
        migrations.RunPython(convert_lighter_type_to_int, convert_lighter_type_to_string),
    ]
