# Generated by Django 6.0.1 on 2026-01-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_remove_custom_pattern_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pattern",
        ),
    ]
